### ISSUE TITLE
Initial checkout will result in error

### ISSUE THREAD

**Issue by bubblegumsoldier** [eliasdarruda/nx-config-splitter#4]
Hey,

first of all great repo!

I have one question: When I put my angular.json into the gitignore and delete it then when someone else checks out the project there will just be an angular.base.json file - no angular.json file. When I then want to generate the initial angular.json file I will receive the following error:

```
> ng generate nx-config-splitter:merge
The generate command requires to be run in an Angular project, but a project definition could not be found.
```

which makes sense because the lack of angular.json file will make the command unavailable.

Wouldn't it be better to have an ng independent command? Right now we have to manually copy the angular.base.json file to angular.json and then again run the command which will in turn update the angular.json file... again. Especially considering a CI-Pipeline environment this is not super nice.

If you need help with a PR for this let me know :)

Kind regards
Henry

**Comment by eliasdarruda** [comment]
Hello, thank you!

Just letting you know that the tool is already tested without an angular environment just using default schematics cli.
It works for react environments using NX too.

**README** is detailing this possibility

```
ng generate nx-config-splitter:merge

or if you don't have ng-cli installed, use the default schematics command instead

schematics nx-config-splitter:merge
```

See if that works for you and let me know
