### ISSUE TITLE
Custom schematic

### ISSUE THREAD

**Issue by bubblegumsoldier** [eliasdarruda/nx-config-splitter#6]
Hey again,
(sry for not answering the first ticket, we found a way)

Now I wanted to add a custom schematic for the project.config.json file. The README is really scarce about that. Where and how to I add that code? What are the imports in the file? Could you please provide a little more info? I tried various methods but there was just too many unknowns.

Will I then have to use a different command than the usual: `ng add @nrwl/angular:lib <name>` command?

**Comment by eliasdarruda** [comment]
> Will I then have to use a different command than the usual: ng add @nrwl/angular:lib <name> command?

The answer to that is yes, you have to run with workspace-schematics provided by NX
NX also provides a tools directory for custom schematics such as this one

You can see more details about how to create a custom Schematic wrapping nx schematic for generating libs here:

https://auth0.com/blog/create-custom-schematics-with-nx/ 

After creating this custom schematic, you wrap the functions in it as it is stated on README

I'll soon update README to give more details too.

**Comment by bubblegumsoldier** [comment]
Okay thanks a lot, I am now at the point where it is doing something but I receive the following error:

```
TypeError: Cannot read property 'projects' of null
    at indexObj (C:\Users\User\repos\erweka\web-client\node_modules\nx-config-splitter\src\commons\configuration-files.js:20:24)
    at indexObj (C:\Users\User\repos\erweka\web-client\node_modules\nx-config-splitter\src\commons\configuration-files.js:15:16)
...
```

My code:

```
import { chain, externalSchematic, Rule } from '@angular-devkit/schematics';

import { writeProjectConfigFiles } from 'nx-config-splitter';

export default function(schema: any): Rule {
    return chain([
        externalSchematic('@nrwl/angular', 'lib', {
            name: schema.name,
        }),
        <any>writeProjectConfigFiles(schema, 'libs', 'nx'),
        writeProjectConfigFiles(schema, 'libs', 'angular', 'projects'),
        writeProjectConfigFiles(schema, 'libs', 'tsconfig', 'compilerOptions.paths'),

        // For nx-react projects
        writeProjectConfigFiles(schema, 'libs', 'workspace', 'projects'),
    ]);
}
```

I had to write the `<any>` before because there seemed to be some type mismatch between the Context in this repo and my version of Nx. I am not sure what the problem is there tbh.

**Comment by eliasdarruda** [comment]
Its either workspace.json or angular.json depending on which file you have in your environment root project folder

So if you don't have a workspace.json file, remove the line or remove for angular.json if you don't have it
